### ISSUE TITLE
Release procedure not complete?

### ISSUE THREAD

**Issue by pietrushnic** [3mdeb/3mdeb-website#112]
https://github.com/3mdeb/3mdeb-website#development-workflow

This procedure stops at the step where we merge the branches to develop, but what is next? We can audit beta.3mdeb.com, and what is the next step?

**Comment by artur-rs** [comment]
@pietrushnic I've slightly changed the phrase `Reporter will verify patch and publish beta env to the production later.` and added 3rd step: https://github.com/3mdeb/3mdeb-website/pull/114
