### ISSUE TITLE
Proposal for Merging Terms of Service with Refund Policy

### ISSUE THREAD

**Issue by gosiastyba** [3mdeb/3mdeb-website#140]
To consider merging these terms of service: https://3mdeb.com/terms-conditions/ with the refund policy: https://3mdeb.com/return-refund-policy/. Everything will be in one place then.
@pietrushnic CC

**Comment by pietrushnic** [comment]
@gosiastyba very good point. @Stanislaw-bnk, let's merge those; eliminating this redundancy would be helpful.
