### ISSUE TITLE
Capitalize "UEFI" everywhere

### ISSUE THREAD

**Issue by pietrushnic** [3mdeb/3mdeb-website#149]
I get reports that not every UEFI occurrence here: https://3mdeb.com/training/#uefi-offensive-security/  is capitalized. Please go through the entire website content and make sure we capitalize this acronym everywhere.

**Comment by Stanislaw-bnk** [comment]
@pietrushnic fixed: https://github.com/3mdeb/3mdeb-website/pull/150

**Comment by macpijan** [comment]
@PLangowski This can also be added to the "trademark" hooks we are adding.
