### ISSUE TITLE
Events - clicking on the ToC reference links doesn't scroll/jump to the target event

### ISSUE THREAD

**Issue by artur-rs** [3mdeb/3mdeb-website#152]
* **Problem:** Clicking on the ToC event link, webiste doesn't scroll to the target event details
* **How to reproduce:** click on the chosen event link in the `Upcoming 2024` or previous years ToC top section
* **Expected behavior** User can freely jump to the chosen event by clicking the ToC event title link

**Comment by Stanislaw-bnk** [comment]
@artur-rs The links work just fine; I tested them on Mozilla and Chrome. The difference is that on Chrome, the page takes much longer to load (30 seconds to 1 minute). Clicking on the link won't work until the website has fully loaded. Unfortunately, I don't know a solution on how to speed up the loading of this page on Chrome.

**Comment by artur-rs** [comment]
Ok, probably something on my side. closing
