### ISSUE TITLE
Deployment problem - rendered site has no layout/styles

### ISSUE THREAD

**Issue by artur-rs** [3mdeb/3mdeb-website#25]
After test deployment (job https://github.com/3mdeb/3mdeb-website/actions/runs/4066328944), website visible on https://3mdeb.github.io/3mdeb-website/ has no styles/layout rendered. Please see the image below:

![3mdeb-test-deployment](https://user-images.githubusercontent.com/32128122/216099278-c676cb13-fc06-437b-b004-6d01d13afa40.png)

**Comment by mehedi-sharif** [comment]
the issue was in the baseURL
now the [baseURL](https://github.com/3mdeb/3mdeb-website/blob/ab1675e48bd7cd58f0dc44a2531eed755d08e43e/config/_default/config.toml#L2) set to - https://3mdeb.github.io/3mdeb-website/
update baseURL when site need to move into https://3mdeb.com/
