### ISSUE TITLE
improvements website 3mdeb.com

### ISSUE THREAD

**Issue by MateuszKochner** [3mdeb/3mdeb-website#28]
1. Delete the text "Contact Form" from the first step on the website  https://3mdeb.com/contact/

**Comment by MateuszKochner** [comment]
@artur-rs hyperlink [Contact Form] [Contact Us] takes you to the same page.

**Comment by artur-rs** [comment]
@MateuszKochner maybe hyperlinks not working correctly - did you verify that?

**Comment by MateuszKochner** [comment]
@artur-rs 
1) hyperlink [Contact Form] should scroll down to form. 
2) hyperlink [Contact us] should not exist because it leads to the same page.

**Comment by pietrushnic** [comment]
@artur-rs, is it still a valid issue?

**Comment by artur-rs** [comment]
I do not see a problem with the same links in the first two steps of the contact us process.
