### ISSUE TITLE
 Old shipping address on shop.3mdeb.com - Return & Refund Policy subpage

### ISSUE THREAD

**Issue by BeataZdunczyk** [3mdeb/3mdeb-website#56]
![image](https://github.com/3mdeb/3mdeb-website/assets/97024713/e018b570-62b3-4d98-9b6f-3eaa29ca7872)

The [Return & Refund Policy](https://shop.3mdeb.com/return-refund-policy/) subpage on the [shop.3mdeb.com](https://shop.3mdeb.com/) website displays an outdated shipping address.

**Comment by artur-rs** [comment]
The issue was fixed on the shop.3mdeb.com subdomain WP instance
