### ISSUE TITLE
Home page/We are Registered section

### ISSUE THREAD

**Issue by BeataZdunczyk** [3mdeb/3mdeb-website#6]
1. The links under the icons, which should redirect with a scroll down to specific sections of the About Us subpage, do not work.
2.  Instead of "we are licensed providers for quality" it should say "Licensed provider for quality"  under the coreboot logo.
![coreboot-text](https://user-images.githubusercontent.com/97024713/213214283-91366d2a-34d4-4d2b-ae4d-db997f7654ec.png)

**Comment by BeataZdunczyk** [comment]
@mehedi-sharif Links don't quite work for "UEFI Adopters" and "Yocto Participants". It doesn't scroll down to those sections.

**Comment by BeataZdunczyk** [comment]
All confirmed

**Comment by tfsojon** [comment]
@BeataZdunczyk Done

**Comment by mehedi-sharif** [comment]
@BeataZdunczyk Done

**Comment by BeataZdunczyk** [comment]
Confirmed, thank you. @artur-rs cc
