### ISSUE TITLE
[Shop] Twonkie product description is outdated

### ISSUE THREAD

**Issue by mkopec** [3mdeb/3mdeb-website#85]
The description of the Twonkie USB-PD sniffer on https://shop.3mdeb.com/shop/open-source-hardware/twonkie-usb-c-sniffer/ is outdated.

> Monitoring VBUS and VCONN voltages and currents (WARNING: VBUS path designed for SPR voltages up to 20V. Not appropriate for use with USB PD 3.1 EPR systems when in EPR mode)

is outdated, should be updated to

> Monitoring VBUS and VCONN voltages and currents (Supports USB PD 3.1 EPR voltages up to 48V)

The original description was accurate only for v1.0 of the product, but we're offering v2.0.

**Comment by Stanislaw-bnk** [comment]
@mkopec fixed https://shop.3mdeb.com/shop/open-source-hardware/twonkie-usb-c-sniffer/
